version: '3'
services:

  api-bannayuu-web-admin:
    image: api-bannayuu-web-admin:1.0.0
    ports:
      - 4501:4501
    volumes:
      - ./volumes/log:/app/dist/logs
      - /home/ubuntu/banayuu_images:/home/ubuntu/banayuu_images
    restart: unless-stopped 
    environment:
      - TZ=Asia/Bangkok
      - NODE_ENV=development
      - DB_HOST=local.uat.bannayuu.com
      - DB_NAME=cit_bannayuu_db
      - DB_PORT=5432
      - DB_USERNAME=cit
      - DB_PASSWORD=db13apr
      - APP_PORT=4501
      - AUTHEN_TOKEN=f56c3775-07b0-45e7-800f-304274533cb7
      - ROOT_IMAGE=/home/ubuntu/banayuu_images/
      - WEB_MANAGEMENT_RESET_USER=https://cit.bannayuu.com/#/reset
      - DB_MAX_IDLE_TIME=10
      - DB_MAX_CONECTIOS=10